### ISSUE TITLE
Using AI agents to contribute to the book

### ISSUE THREAD

**Issue by StoyanStAtanasov** [daveshap/PostLaborEconomics#14]
In your video "LAID OFF BY AI: Day 5: Filled with a terrible resolve! Let's write a collaborative book!" you did not mention AI, AI agents as collaborators. As you already have a repo, code can be added to improve all of the aspects of the book, like readability, citations, graphs, graphics, etc. Then as you add raw content it can be integrated, cleaned up, analyzed and whatever else automatically and rebundled into a fresh living book. Automatically an audiobook can be created. Later with AI video generation a documentary could be generated.

This could be a greater resource than the book itself as when you gather a team of all those people with skills to improve the book they can teach AI agents to do that automatically. This way any book can be improved from now on.

P.S. I'm writing this as an issue as the comments were disabled on the video.

Happy to discuss this further.

**Comment by Vacyyyy** [comment]
At its core, the idea of using AI to make this book multimodal has merit, IMO (it kinda reminds me of the fictional book "System Collapse" by Martha Wells). However, as of right now, I think, the tech isn't quite up for that (even for automated text improvement without human oversight) and is thus currently, unfortunately, not actionable. Luckily, AI is changing *fast*, so this might be possible in a few months.

**Comment by daveshap** [comment]
Thanks for jumping in with your ideas. There would be some value here, however, this constitutes scope creep. Furthermore, there is not much utility in focusing on agents and bots, as not many people use them, and they are experimental. Please review CONTRIBUTING as well as the strategy. These will not be changed. Cheers!

**Comment by StoyanStAtanasov** [comment]
@daveshap The idea has nothing to do with the contents of the book, so you don't have to change anything there. It's a way to improve the book consistent with some of your videos I have seen about higher level thinking with AI.
About the scope creep. It looks like it solves a real problem, how do you update a book about predictions about a quick changing topic and constant influx of new information. Include here discussions, different ideas from contributors. All of this needs to be managed and integrated.


P.S. Maybe it's a topic for the discussions.

Cheers
